### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by JoaoPedroFerreira** [jenkinsci/allure-plugin#172]
### Context
- **Jenkins version**: 2.73.2
- **Job type**: Maven Type

- **Allure plugin version**: 2.24
- **Allure commandline version**: I don´t know

### Problem description
 work on previous version version I update the plugin to  2.24 and I have this log on the jenkins job. Any ideia?

### Logs & Traces

ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:295)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:210)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)

**Comment by phillylovepark** [comment]
Same here, with same plugin version but freestyle job type

ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:295)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:210)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Allure Report' marked build as failure

**Comment by PeterNgTr** [comment]
I got the same error with 2.24

`16:19:13 Allure report was successfully generated.
16:19:13 Creating artifact for the build.
16:19:13 Artifact was added to the build.
16:19:13 ERROR: Build step failed with exception
16:19:13 java.lang.NullPointerException
16:19:13 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:295)
16:19:13 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:210)
16:19:13 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
16:19:13 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:19:13 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
16:19:13 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
16:19:13 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
16:19:13 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
16:19:13 	at hudson.model.Run.execute(Run.java:1762)
16:19:13 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:19:13 	at hudson.model.ResourceController.execute(ResourceController.java:97)
16:19:13 	at hudson.model.Executor.run(Executor.java:421)
16:19:13 Build step 'Allure Report' marked build as failure
16:19:13 Finished: FAILURE`

**Comment by Skylsmoi** [comment]
I have the same issue

I manually reinstalled the version 2.23, it fixed the issue.

**Comment by willtorres** [comment]
Any word on getting this fixed? It's still present in latest version 2.25

**Comment by eroshenkoam** [comment]
https://github.com/jenkinsci/allure-plugin/pull/179/files

**Comment by vnicolev** [comment]
I've updated to the latest version, but the problem still persists.

- Jenkins version: 2.89
- Job type: Maven Type
- Allure plugin version: 2.25

### Logs
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Build step 'Allure Report' marked build as failure

**Comment by PeterNgTr** [comment]
@vnicolev seemed that your allure plugin version is not the latest (which is 2.25.1). Latest version should have the fix.
![allure2 25 1](https://user-images.githubusercontent.com/7845001/34217235-54908660-e5ab-11e7-81ae-979a4bf9bc4a.png)

**Comment by vnicolev** [comment]
You're right! The problem fixed by upgrading to version 2.25.1.
Sorry for my stupid question and thank you for answering it : )

**Comment by premaram** [comment]
I am trying to generate allure report from .TRX files. Though am using latest allure2.5, I still get the same error as below...


llure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Allure Report' marked build as failure

**Comment by jitun2004** [comment]
It might happen due to :
1. Allure is not installed in the Jenkin.

**STEPS:** 

    Go to Manage Jenkins > 
    Global Tool Configuration >
    Allure Commandline > 
    Add Allure Commandline > 
    Uncheck "Install automatically"

Download the latest allure commandline from maven repo - https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/

Unzip the file and provide the location

Installation directory : `C:\allure-2.17.2  (I am using windows, jenkin)`
